// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDhu9qkDAJKymKmGG0EUJoanYDQkXb7kk',
    appId: '1:410892593556:web:b288c6fb51479d59970781',
    messagingSenderId: '410892593556',
    projectId: 'tasksapplication-6bd79',
    authDomain: 'tasksapplication-6bd79.firebaseapp.com',
    storageBucket: 'tasksapplication-6bd79.appspot.com',
    measurementId: 'G-GGP47G0P1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApTvcpLw4UOUY9GocsYfGqP792nzTFRaQ',
    appId: '1:410892593556:android:182664e094e3653c970781',
    messagingSenderId: '410892593556',
    projectId: 'tasksapplication-6bd79',
    storageBucket: 'tasksapplication-6bd79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIeA-Mv6YfGceuWGGPw-SfTg_h8p8xGdE',
    appId: '1:410892593556:ios:a6c70627e53bb66e970781',
    messagingSenderId: '410892593556',
    projectId: 'tasksapplication-6bd79',
    storageBucket: 'tasksapplication-6bd79.appspot.com',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIeA-Mv6YfGceuWGGPw-SfTg_h8p8xGdE',
    appId: '1:410892593556:ios:41dc0ff6732375d1970781',
    messagingSenderId: '410892593556',
    projectId: 'tasksapplication-6bd79',
    storageBucket: 'tasksapplication-6bd79.appspot.com',
    iosBundleId: 'com.example.tasksApp.RunnerTests',
  );
}
